// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLyCubZQOe7pefXC4yenih1AYeR42uhMc',
    appId: '1:884376987703:web:af6611d7524d5da4beb7b2',
    messagingSenderId: '884376987703',
    projectId: 'news-app-c7a53',
    authDomain: 'news-app-c7a53.firebaseapp.com',
    storageBucket: 'news-app-c7a53.appspot.com',
    measurementId: 'G-4NQMMHZNL7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw6UZfI_wLEhbSfdx-MpTW4Ka7fDy9nwc',
    appId: '1:884376987703:android:c603a074de6ff37abeb7b2',
    messagingSenderId: '884376987703',
    projectId: 'news-app-c7a53',
    storageBucket: 'news-app-c7a53.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpwHZ6Mn2HEs-zf2PwnkuT3f4b4ihReF8',
    appId: '1:884376987703:ios:f389c0e4e69eca7abeb7b2',
    messagingSenderId: '884376987703',
    projectId: 'news-app-c7a53',
    storageBucket: 'news-app-c7a53.appspot.com',
    iosClientId: '884376987703-14910aqnajl189qf56ph0le2q5rev774.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpwHZ6Mn2HEs-zf2PwnkuT3f4b4ihReF8',
    appId: '1:884376987703:ios:f389c0e4e69eca7abeb7b2',
    messagingSenderId: '884376987703',
    projectId: 'news-app-c7a53',
    storageBucket: 'news-app-c7a53.appspot.com',
    iosClientId: '884376987703-14910aqnajl189qf56ph0le2q5rev774.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsApi',
  );
}
